// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXPY017lsMMx9PkQKoC_-wC-woRpS8dOo',
    appId: '1:201388432176:web:091d5e04efa103922506f5',
    messagingSenderId: '201388432176',
    projectId: 'appcondominio-5508b',
    authDomain: 'appcondominio-5508b.firebaseapp.com',
    storageBucket: 'appcondominio-5508b.firebasestorage.app',
    measurementId: 'G-2B02YZZJJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMcvlP-hE5xfO-3J-AlR5s2GrVtQoEtow',
    appId: '1:201388432176:android:413d899294d0c1532506f5',
    messagingSenderId: '201388432176',
    projectId: 'appcondominio-5508b',
    storageBucket: 'appcondominio-5508b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '[APIKEY]',
    appId: '1:201388432176:ios:17d633d1718c572b2506f5',
    messagingSenderId: '201388432176',
    projectId: 'appcondominio-5508b',
    storageBucket: 'appcondominio-5508b.firebasestorage.app',
    iosBundleId: 'com.example.appCondominio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '[APIKEY]',
    appId: '1:201388432176:ios:17d633d1718c572b2506f5',
    messagingSenderId: '201388432176',
    projectId: 'appcondominio-5508b',
    storageBucket: 'appcondominio-5508b.firebasestorage.app',
    iosBundleId: 'com.example.appCondominio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXPY017lsMMx9PkQKoC_-wC-woRpS8dOo',
    appId: '1:201388432176:web:06993b4faa956f482506f5',
    messagingSenderId: '201388432176',
    projectId: 'appcondominio-5508b',
    authDomain: 'appcondominio-5508b.firebaseapp.com',
    storageBucket: 'appcondominio-5508b.firebasestorage.app',
    measurementId: 'G-Y73GJS0V1S',
  );
}
